### ISSUE TITLE
Can I use this?

### ISSUE THREAD

**Issue by ghost** [Blockmandoo/BetterProfilePicturesJava#2]
How would I go about using this?

**Comment by Blockhead42** [comment]
I'll add this to the readme, there's a live website you can use [here](https://betterprofilepicturejava.netlify.app).

**Comment by ghost** [comment]
This is actually epic, I love it!

**Comment by Blockmandoo** [comment]
No problem man, this website has honestly been a passion project of mine, enjoy 😀
